<template>
  <v-card>
    <v-toolbar class="cyan" dark dense>
      <v-btn icon @click="pagerouter({name:'deviceInfo'})" dark>
        <v-icon>arrow_back</v-icon>
      </v-btn>
      <v-toolbar-title class="white--text">编辑网络设备</v-toolbar-title>
    </v-toolbar>
    <v-card-text>
      <v-text-field
        label="管理IP"
        v-model="updateDeviceInfo.manageIp"
        v-validate="'required'"
        :error-messages="vee_errors.collect('管理IP','deviceinfo_update')[0]||[]"
        data-vv-name="管理IP"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="设备名称"
        v-model="updateDeviceInfo.deviceName"
        v-validate="'required'"
        :error-messages="vee_errors.collect('设备名称','deviceinfo_update')[0]||[]"
        data-vv-name="设备名称"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="设备别名"
        v-model="updateDeviceInfo.deviceOtherName"
        v-validate="'required'"
        :error-messages="vee_errors.collect('设备别名','deviceinfo_update')[0]||[]"
        data-vv-name="设备别名"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="设备类型"
        v-model="updateDeviceInfo.deviceType"
        v-validate="'required'"
        :error-messages="vee_errors.collect('设备类型','deviceinfo_update')[0]||[]"
        data-vv-name="设备类型"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="设备型号"
        v-model="updateDeviceInfo.deviceVersion"
        v-validate="'required'"
        :error-messages="vee_errors.collect('设备型号','deviceinfo_update')[0]||[]"
        data-vv-name="设备型号"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="设备级别"
        v-model="updateDeviceInfo.deviceLevel"
        v-validate="'required'"
        :error-messages="vee_errors.collect('设备级别','deviceinfo_update')[0]||[]"
        data-vv-name="设备级别"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="SNMP版本"
        v-model="updateDeviceInfo.snmpVersion"
        v-validate="'required'"
        :error-messages="vee_errors.collect('SNMP版本','deviceinfo_update')[0]||[]"
        data-vv-name="SNMP版本"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="SNMP端口"
        v-model="updateDeviceInfo.snmpPort"
        v-validate="'required'"
        :error-messages="vee_errors.collect('SNMP端口','deviceinfo_update')[0]||[]"
        data-vv-name="SNMP端口"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="Community String RO"
        v-model="updateDeviceInfo.communityStringRo"
        v-validate="'required'"
        :error-messages="vee_errors.collect('Community String RO','deviceinfo_update')[0]||[]"
        data-vv-name="Community String RO"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="Community String RW"
        v-model="updateDeviceInfo.communityStringRw"
        v-validate="'required'"
        :error-messages="vee_errors.collect('Community String RW','deviceinfo_update')[0]||[]"
        data-vv-name="Community String RW"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="管理部门"
        v-model="updateDeviceInfo.department"
        v-validate="'required'"
        :error-messages="vee_errors.collect('管理部门','deviceinfo_update')[0]||[]"
        data-vv-name="管理部门"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="所属机构"
        v-model="updateDeviceInfo.attributeOrganization"
        v-validate="'required'"
        :error-messages="vee_errors.collect('所属机构','deviceinfo_update')[0]||[]"
        data-vv-name="所属机构"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="网络区域"
        v-model="updateDeviceInfo.networkZone"
        v-validate="'required'"
        :error-messages="vee_errors.collect('网络区域','deviceinfo_update')[0]||[]"
        data-vv-name="网络区域"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="状态属性"
        v-model="updateDeviceInfo.stat"
        v-validate="'required'"
        :error-messages="vee_errors.collect('状态属性','deviceinfo_update')[0]||[]"
        data-vv-name="状态属性"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="监控策略"
        v-model="updateDeviceInfo.monitorTactics"
        v-validate="'required'"
        :error-messages="vee_errors.collect('监控策略','deviceinfo_update')[0]||[]"
        data-vv-name="监控策略"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="时段策略"
        v-model="updateDeviceInfo.timeTactics"
        v-validate="'required'"
        :error-messages="vee_errors.collect('时段策略','deviceinfo_update')[0]||[]"
        data-vv-name="时段策略"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="备注"
        v-model="updateDeviceInfo.remarks"
        v-validate="'required'"
        :error-messages="vee_errors.collect('备注','deviceinfo_update')[0]||[]"
        data-vv-name="备注"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="厂商"
        v-model="updateDeviceInfo.firm"
        v-validate="'required'"
        :error-messages="vee_errors.collect('厂商','deviceinfo_update')[0]||[]"
        data-vv-name="厂商"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="ObjectID"
        v-model="updateDeviceInfo.objectId"
        v-validate="'required'"
        :error-messages="vee_errors.collect('ObjectID','deviceinfo_update')[0]||[]"
        data-vv-name="ObjectID"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="软件版本"
        v-model="updateDeviceInfo.softwareVersion"
        v-validate="'required'"
        :error-messages="vee_errors.collect('软件版本','deviceinfo_update')[0]||[]"
        data-vv-name="软件版本"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="供应商"
        v-model="updateDeviceInfo.supplier"
        v-validate="'required'"
        :error-messages="vee_errors.collect('供应商','deviceinfo_update')[0]||[]"
        data-vv-name="供应商"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="服务商"
        v-model="updateDeviceInfo.serviceProvider"
        v-validate="'required'"
        :error-messages="vee_errors.collect('服务商','deviceinfo_update')[0]||[]"
        data-vv-name="服务商"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="是否为网点"
        v-model="updateDeviceInfo.whetherDot"
        v-validate="'required'"
        :error-messages="vee_errors.collect('是否为网点','deviceinfo_update')[0]||[]"
        data-vv-name="是否为网点"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="资产编号"
        v-model="updateDeviceInfo.assetId"
        v-validate="'required'"
        :error-messages="vee_errors.collect('资产编号','deviceinfo_update')[0]||[]"
        data-vv-name="资产编号"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="上架时间"
        v-model="updateDeviceInfo.groundingTime"
        v-validate="'required'"
        :error-messages="vee_errors.collect('上架时间','deviceinfo_update')[0]||[]"
        data-vv-name="上架时间"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="机房"
        v-model="updateDeviceInfo.computerRoom"
        v-validate="'required'"
        :error-messages="vee_errors.collect('机房','deviceinfo_update')[0]||[]"
        data-vv-name="机房"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="机柜编号"
        v-model="updateDeviceInfo.computerCounter"
        v-validate="'required'"
        :error-messages="vee_errors.collect('机柜编号','deviceinfo_update')[0]||[]"
        data-vv-name="机柜编号"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="维保开始时间"
        v-model="updateDeviceInfo.maintenanceStartTime"
        v-validate="'required'"
        :error-messages="vee_errors.collect('维保开始时间','deviceinfo_update')[0]||[]"
        data-vv-name="维保开始时间"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="维保结束时间"
        v-model="updateDeviceInfo.maintenanceEndTime"
        v-validate="'required'"
        :error-messages="vee_errors.collect('维保结束时间','deviceinfo_update')[0]||[]"
        data-vv-name="维保结束时间"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="重要端口标识"
        v-model="updateDeviceInfo.importantPort"
        v-validate="'required'"
        :error-messages="vee_errors.collect('重要端口标识','deviceinfo_update')[0]||[]"
        data-vv-name="重要端口标识"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="端口状态"
        v-model="updateDeviceInfo.portStat"
        v-validate="'required'"
        :error-messages="vee_errors.collect('端口状态','deviceinfo_update')[0]||[]"
        data-vv-name="端口状态"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="端口名称"
        v-model="updateDeviceInfo.portName"
        v-validate="'required'"
        :error-messages="vee_errors.collect('端口名称','deviceinfo_update')[0]||[]"
        data-vv-name="端口名称"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="端口别名"
        v-model="updateDeviceInfo.portOtherName"
        v-validate="'required'"
        :error-messages="vee_errors.collect('端口别名','deviceinfo_update')[0]||[]"
        data-vv-name="端口别名"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="端口IP"
        v-model="updateDeviceInfo.portIp"
        v-validate="'required'"
        :error-messages="vee_errors.collect('端口IP','deviceinfo_update')[0]||[]"
        data-vv-name="端口IP"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="带宽（MB）"
        v-model="updateDeviceInfo.bandwidth"
        v-validate="'required'"
        :error-messages="vee_errors.collect('带宽（MB）','deviceinfo_update')[0]||[]"
        data-vv-name="带宽（MB）"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="用户编号"
        v-model="updateDeviceInfo.userId"
        v-validate="'required'"
        :error-messages="vee_errors.collect('用户编号','deviceinfo_update')[0]||[]"
        data-vv-name="用户编号"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>
      <v-text-field
        label="服务器编号"
        v-model="updateDeviceInfo.groupId"
        v-validate="'required'"
        :error-messages="vee_errors.collect('服务器编号','deviceinfo_update')[0]||[]"
        data-vv-name="服务器编号"
        data-vv-scope="deviceinfo_update"
      ></v-text-field>

    </v-card-text>
    <v-card-actions>
      <v-spacer></v-spacer>
      <v-btn color="success" dark @click.stop="deviceinfo_update()">
        <v-icon>check</v-icon>
        更新

      </v-btn>
    </v-card-actions>
  </v-card>
</template>
<script>
  import {axios} from '@/assets/js/Utils';
  import {mapGetters, mapState, mapMutations} from 'vuex';
  import store from '@/store';

  export default {
    beforeRouteEnter (to, from, next) {
      if (!store.state.deviceinfo.updateDeviceInfo) {
        next({name:'deviceInfo'})
      } else {
        next();
      }
    },
    computed: {
      ...mapState('deviceinfo', ['updateDeviceInfo']),
    },
    methods: {
      deviceinfo_update(){
        this.$validator.validateAll("deviceinfo_update").then((result) => {
          if (result) {
            axios().put("/deviceinfo", this.updateDeviceInfo).then(() => {
              this.simpleInfo("操作成功")
              this.pagerouter({name: 'deviceInfo'})
            }).catch((error) => {
              this.simpleError("后台异常,操作失败")
            })
          }
        });
      }
    }
  }
</script>
